<?php
/**
 * Taxonomia — Conhecimento, Mente e Desenvolvimento Pessoal (schema v2).
 *
 * 3 segmentos (editorias) × 10 nichos (subcategorias) com feeds RSS independentes BR.
 *
 * @return array<string, mixed>
 */
return array(
	'schema_version' => 2,
	'portal_id'      => 'estrato-mind',
	'menu_order'     => array(
		'aprendizado-cognicao',
		'filosofia-autoconhecimento',
		'financas-comportamentais',
	),
	'column_order'   => array(),
	'index_order'    => array(
		'aprendizado-cognicao',
		'filosofia-autoconhecimento',
		'financas-comportamentais',
	),
	'legacy_merge'   => array(),
	'legacy_noindex' => array(),
	'defaults'       => array(
		'branding' => array(
			'primary_color'   => '#1B1B2F',
			'accent_color'    => '#7B68EE',
			'secondary_color' => '#2D2D44',
			'header_variant'  => 'editoria',
		),
		'keywords' => array(
			'include'  => array(),
			'exclude'  => array(),
			'match_in' => array( 'title', 'excerpt', 'content' ),
		),
	),
	'categories'     => array(
		'aprendizado-cognicao' => array(
			'name'        => 'Aprendizado & Cognição',
			'description' => 'Produtividade intencional, segundo cérebro, técnicas de estudo baseadas em evidência e aprendizado autodidata de idiomas.',
			'branding'    => array(
				'brand_name'      => 'Aprendizado',
				'primary_color'   => '#1A365D',
				'accent_color'    => '#63B3ED',
				'secondary_color' => '#2C5282',
				'header_variant'  => 'editoria',
			),
			'keywords'    => array(
				'include' => array(),
				'exclude' => array( 'ibovespa', 'selic', 'copom', 'bitcoin' ),
			),
			'feeds'       => array(
				array(
					'title'    => 'TabNews',
					'url'      => 'https://www.tabnews.com.br/recentes/rss',
					'tier'     => 1,
					'verified' => true,
				),
			),
			'subcategories' => array(
				'produtividade-minimalismo' => array(
					'name'        => 'Produtividade não tóxica',
					'description' => 'Minimalismo digital, foco, detox e uso intencional de tecnologia.',
					'keywords'    => array(
						'include' => array(
							'minimalismo digital',
							'produtividade não tóxica',
							'produtividade nao toxica',
							'foco atenção',
							'foco atencao',
							'detox digital',
							'uso intencional',
							'slow web',
						),
						'exclude' => array(),
					),
					'feeds'       => array(
						array( 'title' => 'Manual do Usuário', 'url' => 'https://manualdousuario.net/feed/', 'tier' => 1 ),
						array( 'title' => 'Sua Produtividade', 'url' => 'https://suaprodutividade.com.br/feed/', 'tier' => 2 ),
						array(
							'title'    => 'TabNews',
							'url'      => 'https://www.tabnews.com.br/recentes/rss',
							'tier'     => 1,
							'verified' => true,
							'keywords' => array(
								'include' => array( 'produtividade', 'foco', 'minimalismo', 'detox', 'atenção', 'atencao' ),
								'exclude' => array(),
							),
						),
					),
				),
				'segundo-cebre-pkm'         => array(
					'name'        => 'Segundo cérebro & PKM',
					'description' => 'Obsidian, Notion, Logseq, Zettelkasten e organização de notas.',
					'keywords'    => array(
						'include' => array(
							'segundo cérebro',
							'segundo cerebro',
							'obsidian',
							'zettelkasten',
							'pkm',
							'notion',
							'logseq',
							'para método',
							'para metodo',
						),
						'exclude' => array(),
					),
					'feeds'       => array(
						array(
							'title'    => 'TabNews',
							'url'      => 'https://www.tabnews.com.br/recentes/rss',
							'tier'     => 1,
							'verified' => true,
							'keywords' => array(
								'include' => array( 'obsidian', 'zettelkasten', 'pkm', 'notion', 'logseq', 'segundo cérebro', 'segundo cerebro' ),
								'exclude' => array(),
							),
						),
						array( 'title' => 'João Martins Filho', 'url' => 'https://joaomartinsfilho.substack.com/feed', 'tier' => 1 ),
					),
				),
				'estudo-evidencia'          => array(
					'name'        => 'Estudo baseado em evidência',
					'description' => 'Active recall, repetição espaçada e ciência cognitiva aplicada ao aprendizado.',
					'keywords'    => array(
						'include' => array(
							'recuperação ativa',
							'recuperacao ativa',
							'repetição espaçada',
							'repeticao espacada',
							'active recall',
							'técnicas de estudo',
							'tecnicas de estudo',
							'curva do esquecimento',
							'flashcard',
						),
						'exclude' => array(),
					),
					'feeds'       => array(
						array( 'title' => 'Rafael Bianco', 'url' => 'https://rafaelbianco.substack.com/feed', 'tier' => 1 ),
						array(
							'title'    => 'TabNews',
							'url'      => 'https://www.tabnews.com.br/recentes/rss',
							'tier'     => 2,
							'verified' => true,
							'keywords' => array(
								'include' => array( 'estudo', 'aprendizado', 'memória', 'memoria', 'recall', 'espaçad', 'espacad' ),
								'exclude' => array(),
							),
						),
					),
				),
				'idiomas-imersao'           => array(
					'name'        => 'Idiomas & imersão',
					'description' => 'Input compreensível, imersão e aquisição autodidata de línguas.',
					'keywords'    => array(
						'include' => array(
							'input compreensível',
							'input compreensivel',
							'imersão idioma',
							'imersao idioma',
							'aprender inglês',
							'aprender ingles',
							'aquisição linguística',
							'aquisicao linguistica',
							'poliglota',
						),
						'exclude' => array(),
					),
					'feeds'       => array(
						array( 'title' => 'Laura Escreve', 'url' => 'https://lauraescreve.substack.com/feed', 'tier' => 1 ),
						array( 'title' => 'Apure Guria', 'url' => 'https://apureguria.com/feed/', 'tier' => 2 ),
					),
				),
			),
		),
		'filosofia-autoconhecimento' => array(
			'name'        => 'Filosofia & Autoconhecimento',
			'description' => 'Estoicismo prático, journaling, meditação e neurociência contemplativa.',
			'branding'    => array(
				'brand_name'      => 'Mente',
				'primary_color'   => '#2D1B4E',
				'accent_color'    => '#B794F4',
				'secondary_color' => '#44337A',
				'header_variant'  => 'editoria',
			),
			'keywords'    => array(
				'include' => array(),
				'exclude' => array( 'ibovespa', 'selic', 'bitcoin', 'criptomoeda' ),
			),
			'feeds'       => array(),
			'subcategories' => array(
				'estoicismo'              => array(
					'name'        => 'Estoicismo prático',
					'description' => 'Filosofia estoica aplicada ao cotidiano: dicotomia do controle, virtude e resiliência.',
					'keywords'    => array(
						'include' => array(
							'estoicismo',
							'dicotomia do controle',
							'marco aurélio',
							'marco aurelio',
							'sêneca',
							'seneca',
							'epicteto',
							'filosofia prática',
							'filosofia pratica',
							'virtude estoica',
						),
						'exclude' => array(),
					),
					'feeds'       => array(
						array( 'title' => 'Prática Estóica', 'url' => 'https://praticaestoica.substack.com/feed', 'tier' => 1 ),
						array( 'title' => 'Expresso Existencial', 'url' => 'https://expressoexistencial.substack.com/feed', 'tier' => 3 ),
					),
				),
				'journaling'              => array(
					'name'        => 'Journaling & escrita terapêutica',
					'description' => 'Escrita expressiva, diário emocional e autoconhecimento por escrita.',
					'keywords'    => array(
						'include' => array(
							'escrita terapêutica',
							'escrita terapeutica',
							'journaling',
							'escrita expressiva',
							'diário emocional',
							'diario emocional',
							'pennebaker',
							'biblioterapia',
						),
						'exclude' => array(),
					),
					'feeds'       => array(
						array(
							'title' => 'Reescrevendo a Sua História',
							'url'   => 'https://www.reescrevendoasuahistoria.net.br/feeds/posts/default?alt=rss',
							'tier'  => 1,
						),
						array(
							'title'    => 'Rafael Bianco',
							'url'      => 'https://rafaelbianco.substack.com/feed',
							'tier'     => 2,
							'keywords' => array(
								'include' => array( 'journaling', 'escrita', 'diário', 'diario', 'terapêutica', 'terapeutica' ),
								'exclude' => array(),
							),
						),
					),
				),
				'meditacao-neurociencia'  => array(
					'name'        => 'Meditação & neurociência',
					'description' => 'Mindfulness, MBSR, neuroplasticidade e ciência contemplativa.',
					'keywords'    => array(
						'include' => array(
							'neurociência contemplativa',
							'neurociencia contemplativa',
							'mindfulness',
							'meditação',
							'meditacao',
							'atenção plena',
							'atencao plena',
							'mbsr',
							'neuroplasticidade',
						),
						'exclude' => array(),
					),
					'feeds'       => array(
						array( 'title' => 'Instituto EntreSer', 'url' => 'https://www.institutoentreser.com.br/feed/', 'tier' => 1 ),
						array( 'title' => 'Mundo Mindfulness', 'url' => 'https://mundomindfulness.com.br/feed/', 'tier' => 2 ),
						array( 'title' => 'Ciência Contemplativa', 'url' => 'https://novo.cienciacontemplativa.org/feed/', 'tier' => 2 ),
					),
				),
			),
		),
		'financas-comportamentais' => array(
			'name'        => 'Finanças Comportamentais',
			'description' => 'Psicologia econômica, finanças para autônomos e movimento FIRE brasileiro.',
			'branding'    => array(
				'brand_name'      => 'Comportamento',
				'primary_color'   => '#234E52',
				'accent_color'    => '#4FD1C5',
				'secondary_color' => '#285E61',
				'header_variant'  => 'editoria',
			),
			'keywords'    => array(
				'include' => array(),
				'exclude' => array( 'ibovespa', 'pregão', 'pregao' ),
			),
			'feeds'       => array(
				array(
					'title'    => 'AA40 — Aposente aos 40',
					'url'      => 'https://aposenteaos40.org/feed/',
					'tier'     => 1,
					'verified' => true,
				),
			),
			'subcategories' => array(
				'psicologia-economica' => array(
					'name'        => 'Psicologia econômica',
					'description' => 'Vieses cognitivos, heurísticas e economia comportamental no cotidiano.',
					'keywords'    => array(
						'include' => array(
							'vieses cognitivos',
							'economia comportamental',
							'heurísticas',
							'heuristicas',
							'kahneman',
							'thaler',
							'finanças comportamentais',
							'financas comportamentais',
							'racionalidade limitada',
						),
						'exclude' => array(),
					),
					'feeds'       => array(
						array( 'title' => 'Blog do IBRE (FGV)', 'url' => 'https://blogdoibre.fgv.br/rss.xml', 'tier' => 2 ),
						array(
							'title'    => 'TabNews',
							'url'      => 'https://www.tabnews.com.br/recentes/rss',
							'tier'     => 2,
							'verified' => true,
							'keywords' => array(
								'include' => array( 'viés', 'vies', 'comportamental', 'heurística', 'heuristica', 'kahneman', 'decisão', 'decisao' ),
								'exclude' => array(),
							),
						),
					),
				),
				'financas-autonomos'   => array(
					'name'        => 'Finanças para autônomos',
					'description' => 'Freelancers, MEI, precificação, fluxo de caixa e reserva de emergência.',
					'keywords'    => array(
						'include' => array(
							'finanças autônomo',
							'financas autonomo',
							'mei',
							'freelancer',
							'precificação',
							'precificacao',
							'renda variável',
							'reserva de emergência',
							'reserva de emergencia',
							'nômade digital',
							'nomade digital',
						),
						'exclude' => array(),
					),
					'feeds'       => array(
						array( 'title' => 'Vivendo de Freela', 'url' => 'https://www.vivendodefreela.com.br/feed/', 'tier' => 1 ),
						array( 'title' => 'Viagem Lenta', 'url' => 'https://viagemlenta.com/feed/', 'tier' => 1 ),
					),
				),
				'fire-consumo'         => array(
					'name'        => 'FIRE & consumo consciente',
					'description' => 'Independência financeira, frugalidade, taxa segura de retirada e FIRESFERA brasileira.',
					'keywords'    => array(
						'include' => array(
							'fire brasil',
							'independência financeira',
							'independencia financeira',
							'taxa segura',
							'consumo consciente',
							'frugalidade',
							'minimalismo',
							'aposentadoria antecipada',
							'firesfera',
						),
						'exclude' => array(),
					),
					'feeds'       => array(
						array(
							'title'    => 'AA40 — Aposente aos 40',
							'url'      => 'https://aposenteaos40.org/feed/',
							'tier'     => 1,
							'verified' => true,
						),
						array(
							'title'    => 'Bilionário do Zero',
							'url'      => 'https://bilionariodozero.blogspot.com/feeds/posts/default?alt=rss',
							'tier'     => 1,
							'verified' => true,
						),
						array(
							'title' => 'Quero virar Vagabundo',
							'url'   => 'https://querovirarvagabundo.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 1,
						),
						array(
							'title' => 'FIRE Arroz com Feijão',
							'url'   => 'https://firearrozcomfeijao.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 1,
						),
						array(
							'title' => 'Professora FIRE',
							'url'   => 'https://professorafire.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 1,
						),
						array(
							'title' => 'Investidor Inglês | Rumo a Independência Financeira',
							'url'   => 'https://investidoringles.com/feed/',
							'tier'  => 1,
							'firesfera' => true,
						),
						array(
							'title' => 'Viagem Lenta',
							'url'   => 'https://www.viagemlenta.com/feed/',
							'tier'  => 1,
							'firesfera' => true,
						),
						array(
							'title' => 'Scant SA',
							'url'   => 'https://scantsa.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Investidor Top',
							'url'   => 'http://www.investidortop.com.br/feed/',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Vou Empreender e Agora?',
							'url'   => 'https://vouempreendereagora.com.br/feed/',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Mendigo Investidor',
							'url'   => 'https://mendigoinvestidor.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Independência Financeira ou Morte',
							'url'   => 'http://independenciafinanceiraoumorte.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'O Mentor Financeiro',
							'url'   => 'https://omentorfinanceiro.com.br/feed/',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Jardim Epicurista',
							'url'   => 'http://jardimepicurista.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Neto Financista do Velho Barreiro',
							'url'   => 'https://netofinancistadovelhobarreiro.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'A Vaca Leiteira',
							'url'   => 'https://vacaleiteiraholding.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Além da Independência Financeira',
							'url'   => 'https://alemdaindependenciafinanceira.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Aportador Indeciso',
							'url'   => 'http://aportadorindeciso.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Aporte Hoje',
							'url'   => 'https://aportehoje.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Caminho das Pedras FIRE',
							'url'   => 'https://caminhodaspedrasfire.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Capital e Liberdade',
							'url'   => 'https://capitaleliberdade.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Capital Fantástico!',
							'url'   => 'http://capitalfantastico.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Chrono Fire',
							'url'   => 'http://chronofire16.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Cia Expert',
							'url'   => 'https://www.ciaexpert.com.br/rss.xml',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Conexão Financeira',
							'url'   => 'http://www.conexaofinanceira.com.br/feed/',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Consciente Escolha',
							'url'   => 'https://conscienteescolha.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Eletricista Investidor',
							'url'   => 'https://eletricistainvestidor.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Engenharia dos Investimentos',
							'url'   => 'https://engenhariadosinvestimentos.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Engenheiro Mendigo',
							'url'   => 'https://engenheiromendigo.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Engenheiro Tardio',
							'url'   => 'https://engenheirotardio.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Estoico Investidor',
							'url'   => 'https://estoicoinvestidor.wordpress.com/feed/',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Fazendo as Contas',
							'url'   => 'https://www.fazendoascontas.com.br/rss.xml',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'FinanceiraMente',
							'url'   => 'https://finmente.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Foco no Milhão',
							'url'   => 'https://foconomilhao.com/feed/',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Frugal Simples',
							'url'   => 'https://frugalsimples.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'IR Finanças',
							'url'   => 'https://investindorapido.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Jornada Nikkei',
							'url'   => 'https://jornadanikkei.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Jornada Simples',
							'url'   => 'https://jornadasimples.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Jumbo Frugal',
							'url'   => 'http://jumbofrugal.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Lady Fire Blog',
							'url'   => 'https://ladyfire20465733.wordpress.com/feed/',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Ler e Poupar',
							'url'   => 'http://lerepoupar.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Maromba Investidor',
							'url'   => 'https://marombainvestidor.com/feed/',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Med Life - Investimentos, Medicina e Treinos',
							'url'   => 'https://medlifeinvestimentos.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Monster Investidor',
							'url'   => 'http://monsterinvestimentos.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'O Aportador Financeiro',
							'url'   => 'https://oaportadorfinanceiro.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'O aportador obstinado',
							'url'   => 'https://aportadorobstinado.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Patrimônio Zero',
							'url'   => 'http://patrimoniozero.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Policial Investidor',
							'url'   => 'https://policialinvestidor.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Poupando Centavos',
							'url'   => 'http://poupandocentavos.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Projeto fire classe D',
							'url'   => 'https://projetofireclassed.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'quase aposentado',
							'url'   => 'https://aposentado39.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Seja Independente',
							'url'   => 'https://blogsejaindependente.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Semeador Financeiro',
							'url'   => 'https://semeadorfinanceiro.wordpress.com/feed/',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Sísifo Aposentado',
							'url'   => 'https://sisifoaposentado.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Sócio Rico',
							'url'   => 'https://sociorico.com/feed/',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'turko investidor',
							'url'   => 'https://turkoinvestidor.blogspot.com/feeds/posts/default?alt=rss',
							'tier'  => 2,
							'firesfera' => true,
						),
						array(
							'title' => 'Viver Sem Pressa',
							'url'   => 'https://viversempressa.com/feed/',
							'tier'  => 2,
							'firesfera' => true,
						),
				),
			),
		),
	),
	'columns'        => array(),
);
